# frozen_string_literal: true

require 'rapid/api'
require 'rapid/argument_set'
require 'rapid/authenticator'
require 'rapid/controller'
require 'rapid/endpoint'
require 'rapid/enum'
require 'rapid/error'
require 'rapid/lookup_argument_set'
require 'rapid/scalar'
require 'rapid/object'
require 'rapid/polymorph'

require 'rapid/scalars/string'
require 'rapid/scalars/integer'
require 'rapid/scalars/boolean'
require 'rapid/scalars/date'
require 'rapid/scalars/unix_time'
require 'rapid/scalars/decimal'
require 'rapid/scalars/base64'
